<?php

namespace System\Classes\Passport;

return [
    // 常用
    ['en' => 'China', 'iso' => 'CN', 'py' => '#', 'zh' => '中国', 'cty' => 86],
    ['en' => 'Hong Kong', 'iso' => 'HK', 'py' => '#', 'zh' => '中国香港', 'cty' => 852],
    ['en' => 'Macau', 'iso' => 'MO', 'py' => '#', 'zh' => '中国澳门', 'cty' => 853],
    ['en' => 'Taiwan', 'iso' => 'TW', 'py' => '#', 'zh' => '中国台湾', 'cty' => 886],

    ['en' => 'Afghanistan', 'iso' => 'AF', 'py' => 'a', 'zh' => '阿富汗', 'cty' => 93],
    ['en' => 'Albania', 'iso' => 'AL', 'py' => 'a', 'zh' => '阿尔巴尼亚', 'cty' => 355],
    ['en' => 'Algeria', 'iso' => 'DZ', 'py' => 'a', 'zh' => '阿尔及利亚', 'cty' => 213],
    ['en' => 'American Samoa', 'iso' => 'AS', 'py' => 'm', 'zh' => '美属萨摩亚', 'cty' => 1684],
    ['en' => 'Andorra', 'iso' => 'AD ', 'py' => 'a', 'zh' => '安道尔', 'cty' => 376],
    ['en' => 'Angola', 'iso' => 'AO', 'py' => 'a', 'zh' => '安哥拉', 'cty' => 244],
    ['en' => 'Anguilla', 'iso' => 'AI', 'py' => 'a', 'zh' => '安圭拉', 'cty' => 1264],
    ['en' => 'Antigua and Barbuda', 'iso' => 'AG', 'py' => 'a', 'zh' => '安提瓜和巴布达', 'cty' => 1268],
    ['en' => 'Argentina', 'iso' => 'AR', 'py' => 'a', 'zh' => '阿根廷', 'cty' => 54],
    ['en' => 'Armenia', 'iso' => 'AM', 'py' => 'y', 'zh' => '亚美尼亚', 'cty' => 374],
    ['en' => 'Aruba', 'iso' => 'AW', 'py' => 'a', 'zh' => '阿鲁巴', 'cty' => 297],
    ['en' => 'Australia', 'iso' => 'AU', 'py' => 'a', 'zh' => '澳大利亚', 'cty' => 61],
    ['en' => 'Austria', 'iso' => 'AT', 'py' => 'a', 'zh' => '奥地利', 'cty' => 43],
    ['en' => 'Azerbaijan', 'iso' => 'AZ', 'py' => 'a', 'zh' => '阿塞拜疆', 'cty' => 994],
    ['en' => 'Bahamas', 'iso' => 'BS', 'py' => 'b', 'zh' => '巴哈马', 'cty' => 1242],
    ['en' => 'Bahrain', 'iso' => 'BH', 'py' => 'b', 'zh' => '巴林', 'cty' => 973],
    ['en' => 'Bangladesh', 'iso' => 'BD', 'py' => 'm', 'zh' => '孟加拉国', 'cty' => 880],
    ['en' => 'Barbados', 'iso' => 'BB', 'py' => 'b', 'zh' => '巴巴多斯', 'cty' => 1246],
    ['en' => 'Belarus', 'iso' => 'BY', 'py' => 'b', 'zh' => '白俄罗斯', 'cty' => 375],
    ['en' => 'Belgium', 'iso' => 'BE', 'py' => 'b', 'zh' => '比利时', 'cty' => 32],
    ['en' => 'Belize', 'iso' => 'BZ', 'py' => 'b', 'zh' => '伯利兹', 'cty' => 501],
    ['en' => 'Benin', 'iso' => 'BJ', 'py' => 'b', 'zh' => '贝宁', 'cty' => 229],
    ['en' => 'Bermuda', 'iso' => 'BM', 'py' => 'b', 'zh' => '百慕大群岛', 'cty' => 1441],
    ['en' => 'Bhutan', 'iso' => 'BT', 'py' => 'b', 'zh' => '不丹', 'cty' => 975],
    ['en' => 'Bolivia', 'iso' => 'BO', 'py' => 'b', 'zh' => '玻利维亚', 'cty' => 591],
    ['en' => 'Bosnia and Herzegovina', 'iso' => 'BA', 'py' => 'b', 'zh' => '波斯尼亚和黑塞哥维那', 'cty' => 387],
    ['en' => 'Botswana', 'iso' => 'BW', 'py' => 'b', 'zh' => '博茨瓦纳', 'cty' => 267],
    ['en' => 'Brazil', 'iso' => 'BR', 'py' => 'b', 'zh' => '巴西', 'cty' => 55],
    ['en' => 'Brunei', 'iso' => 'BN', 'py' => 'w', 'zh' => '文莱', 'cty' => 673],
    ['en' => 'Bulgaria', 'iso' => 'BG', 'py' => 'b', 'zh' => '保加利亚', 'cty' => 359],
    ['en' => 'Burkina Faso', 'iso' => 'BF', 'py' => 'b', 'zh' => '布基纳法索', 'cty' => 226],
    ['en' => 'Burundi', 'iso' => 'BI', 'py' => 'b', 'zh' => '布隆迪', 'cty' => 257],
    ['en' => 'Cambodia', 'iso' => 'KH', 'py' => 'j', 'zh' => '柬埔寨', 'cty' => 855],
    ['en' => 'Cameroon', 'iso' => 'CM', 'py' => 'k', 'zh' => '喀麦隆', 'cty' => 237],
    ['en' => 'Canada', 'iso' => 'CA', 'py' => 'j', 'zh' => '加拿大', 'cty' => 1],
    ['en' => 'Cape Verde', 'iso' => 'CV', 'py' => 'k', 'zh' => '开普', 'cty' => 238],
    ['en' => 'Cayman Islands', 'iso' => 'KY', 'py' => 'k', 'zh' => '开曼群岛', 'cty' => 1345],
    ['en' => 'Central African Republic', 'iso' => 'CF', 'py' => 'z', 'zh' => '中非共和国', 'cty' => 236],
    ['en' => 'Chad', 'iso' => 'TD', 'py' => 'z', 'zh' => '乍得', 'cty' => 235],
    ['en' => 'Chile', 'iso' => 'CL', 'py' => 'z', 'zh' => '智利', 'cty' => 56],
    ['en' => 'China', 'iso' => 'CN', 'py' => 'z', 'zh' => '中国', 'cty' => 86],
    ['en' => 'Colombia', 'iso' => 'CO', 'py' => 'g', 'zh' => '哥伦比亚', 'cty' => 57],
    ['en' => 'Comoros', 'iso' => 'KM', 'py' => 'k', 'zh' => '科摩罗', 'cty' => 269],
    ['en' => 'Cook Islands', 'iso' => 'CK', 'py' => 'k', 'zh' => '库克群岛', 'cty' => 682],
    ['en' => 'Costa Rica', 'iso' => 'CR', 'py' => 'g', 'zh' => '哥斯达黎加', 'cty' => 506],
    ['en' => 'Croatia', 'iso' => 'HR', 'py' => 'k', 'zh' => '克罗地亚', 'cty' => 385],
    ['en' => 'Cuba', 'iso' => 'CU', 'py' => 'g', 'zh' => '古巴', 'cty' => 53],
    ['en' => 'Curacao', 'iso' => 'CW', 'py' => 'k', 'zh' => '库拉索', 'cty' => 599],
    ['en' => 'Cyprus', 'iso' => 'CY', 'py' => 's', 'zh' => '塞浦路斯', 'cty' => 357],
    ['en' => 'Czech', 'iso' => 'CZ', 'py' => 'j', 'zh' => '捷克', 'cty' => 420],
    ['en' => 'Democratic Republic of the Congo', 'iso' => 'CD', 'py' => 'g', 'zh' => '刚果民主共和国', 'cty' => 243],
    ['en' => 'Denmark', 'iso' => 'DK', 'py' => 'd', 'zh' => '丹麦', 'cty' => 45],
    ['en' => 'Djibouti', 'iso' => 'DJ', 'py' => 'j', 'zh' => '吉布提', 'cty' => 253],
    ['en' => 'Dominica', 'iso' => 'DM', 'py' => 'd', 'zh' => '多米尼加', 'cty' => 1767],
    ['en' => 'Dominican Republic', 'iso' => 'DO', 'py' => 'd', 'zh' => '多米尼加共和国', 'cty' => 1809],
    ['en' => 'Ecuador', 'iso' => 'EC', 'py' => 'e', 'zh' => '厄瓜多尔', 'cty' => 593],
    ['en' => 'Egypt', 'iso' => 'EG', 'py' => 'e', 'zh' => '埃及', 'cty' => 20],
    ['en' => 'El Salvador', 'iso' => 'SV', 'py' => 's', 'zh' => '萨尔瓦多', 'cty' => 503],
    ['en' => 'Equatorial Guinea', 'iso' => 'GQ', 'py' => 'c', 'zh' => '赤道几内亚', 'cty' => 240],
    ['en' => 'Eritrea', 'iso' => 'ER', 'py' => 'e', 'zh' => '厄立特里亚', 'cty' => 291],
    ['en' => 'Estonia', 'iso' => 'EE', 'py' => 'a', 'zh' => '爱沙尼亚', 'cty' => 372],
    ['en' => 'Ethiopia', 'iso' => 'ET', 'py' => 'a', 'zh' => '埃塞俄比亚', 'cty' => 251],
    ['en' => 'Faroe Islands', 'iso' => 'FO', 'py' => 'f', 'zh' => '法罗群岛', 'cty' => 298],
    ['en' => 'Fiji', 'iso' => 'FJ', 'py' => 'f', 'zh' => '斐济', 'cty' => 679],
    ['en' => 'Finland', 'iso' => 'FI', 'py' => 'f', 'zh' => '芬兰', 'cty' => 358],
    ['en' => 'France', 'iso' => 'FR', 'py' => 'f', 'zh' => '法国', 'cty' => 33],
    ['en' => 'French Guiana', 'iso' => 'GF', 'py' => 'f', 'zh' => '法属圭亚那', 'cty' => 594],
    ['en' => 'French Polynesia', 'iso' => 'PF', 'py' => 'f', 'zh' => '法属波利尼西亚', 'cty' => 689],
    ['en' => 'Gabon', 'iso' => 'GA', 'py' => 'j', 'zh' => '加蓬', 'cty' => 241],
    ['en' => 'Gambia', 'iso' => 'GM', 'py' => 'g', 'zh' => '冈比亚', 'cty' => 220],
    ['en' => 'Georgia', 'iso' => 'GE', 'py' => 'g', 'zh' => '格鲁吉亚', 'cty' => 995],
    ['en' => 'Germany', 'iso' => 'DE', 'py' => 'd', 'zh' => '德国', 'cty' => 49],
    ['en' => 'Ghana', 'iso' => 'GH', 'py' => 'j', 'zh' => '加纳', 'cty' => 233],
    ['en' => 'Gibraltar', 'iso' => 'GI', 'py' => 'z', 'zh' => '直布罗陀', 'cty' => 350],
    ['en' => 'Greece', 'iso' => 'GR', 'py' => 'x', 'zh' => '希腊', 'cty' => 30],
    ['en' => 'Greenland', 'iso' => 'GL', 'py' => 'g', 'zh' => '格陵兰岛', 'cty' => 299],
    ['en' => 'Grenada', 'iso' => 'GD', 'py' => 'g', 'zh' => '格林纳达', 'cty' => 1473],
    ['en' => 'Guadeloupe', 'iso' => 'GP', 'py' => 'g', 'zh' => '瓜德罗普岛', 'cty' => 590],
    ['en' => 'Guam', 'iso' => 'GU', 'py' => 'g', 'zh' => '关岛', 'cty' => 1671],
    ['en' => 'Guatemala', 'iso' => 'GT', 'py' => 'g', 'zh' => '瓜地马拉', 'cty' => 502],
    ['en' => 'Guinea', 'iso' => 'GN', 'py' => 'j', 'zh' => '几内亚', 'cty' => 224],
    ['en' => 'Guinea-Bissau', 'iso' => 'GW', 'py' => 'j', 'zh' => '几内亚比绍共和国', 'cty' => 245],
    ['en' => 'Guyana', 'iso' => 'GY', 'py' => 'g', 'zh' => '圭亚那', 'cty' => 592],
    ['en' => 'Haiti', 'iso' => 'HT', 'py' => 'h', 'zh' => '海地', 'cty' => 509],
    ['en' => 'Honduras', 'iso' => 'HN', 'py' => 'h', 'zh' => '洪都拉斯', 'cty' => 504],
    ['en' => 'Hong Kong', 'iso' => 'HK', 'py' => 'z', 'zh' => '中国香港', 'cty' => 852],
    ['en' => 'Hungary', 'iso' => 'HU', 'py' => 'x', 'zh' => '匈牙利', 'cty' => 36],
    ['en' => 'Iceland', 'iso' => 'IS', 'py' => 'b', 'zh' => '冰岛', 'cty' => 354],
    ['en' => 'India', 'iso' => 'IN', 'py' => 'y', 'zh' => '印度', 'cty' => 91],
    ['en' => 'Indonesia', 'iso' => 'ID', 'py' => 'y', 'zh' => '印度尼西亚', 'cty' => 62],
    ['en' => 'Iran', 'iso' => 'IR', 'py' => 'y', 'zh' => '伊朗', 'cty' => 98],
    ['en' => 'Iraq', 'iso' => 'IQ', 'py' => 'y', 'zh' => '伊拉克', 'cty' => 964],
    ['en' => 'Ireland', 'iso' => 'IE', 'py' => 'a', 'zh' => '爱尔兰', 'cty' => 353],
    ['en' => 'Israel', 'iso' => 'IL', 'py' => 'y', 'zh' => '以色列', 'cty' => 972],
    ['en' => 'Italy', 'iso' => 'IT', 'py' => 'y', 'zh' => '意大利', 'cty' => 39],
    ['en' => 'Ivory Coast', 'iso' => 'CI', 'py' => 'x', 'zh' => '象牙海岸', 'cty' => 225],
    ['en' => 'Jamaica', 'iso' => 'JM', 'py' => 'y', 'zh' => '牙买加', 'cty' => 1876],
    ['en' => 'Japan', 'iso' => 'JP', 'py' => 'r', 'zh' => '日本', 'cty' => 81],
    ['en' => 'Jordan', 'iso' => 'JO', 'py' => 'y', 'zh' => '约旦', 'cty' => 962],
    ['en' => 'Kazakhstan', 'iso' => 'KZ', 'py' => 'h', 'zh' => '哈萨克斯坦', 'cty' => 7],
    ['en' => 'Kenya', 'iso' => 'KE', 'py' => 'k', 'zh' => '肯尼亚', 'cty' => 254],
    ['en' => 'Kiribati', 'iso' => 'KI', 'py' => 'j', 'zh' => '基里巴斯', 'cty' => 686],
    ['en' => 'Kuwait', 'iso' => 'KW', 'py' => 'k', 'zh' => '科威特', 'cty' => 965],
    ['en' => 'Kyrgyzstan', 'iso' => 'KG', 'py' => 'j', 'zh' => '吉尔吉斯斯坦', 'cty' => 996],
    ['en' => 'Laos', 'iso' => 'LA', 'py' => 'l', 'zh' => '老挝', 'cty' => 856],
    ['en' => 'Latvia', 'iso' => 'LV', 'py' => 'l', 'zh' => '拉脱维亚', 'cty' => 371],
    ['en' => 'Lebanon', 'iso' => 'LB', 'py' => 'l', 'zh' => '黎巴嫩', 'cty' => 961],
    ['en' => 'Lesotho', 'iso' => 'LS', 'py' => 'l', 'zh' => '莱索托', 'cty' => 266],
    ['en' => 'Liberia', 'iso' => 'LR', 'py' => 'l', 'zh' => '利比里亚', 'cty' => 231],
    ['en' => 'Libya', 'iso' => 'LY', 'py' => 'l', 'zh' => '利比亚', 'cty' => 218],
    ['en' => 'Liechtenstein', 'iso' => 'LI', 'py' => 'l', 'zh' => '列支敦士登', 'cty' => 423],
    ['en' => 'Lithuania', 'iso' => 'LT', 'py' => 'l', 'zh' => '立陶宛', 'cty' => 370],
    ['en' => 'Luxembourg', 'iso' => 'LU', 'py' => 'l', 'zh' => '卢森堡', 'cty' => 352],
    ['en' => 'Macau', 'iso' => 'MO', 'py' => 'z', 'zh' => '中国澳门', 'cty' => 853],
    ['en' => 'Macedonia', 'iso' => 'MK', 'py' => 'm', 'zh' => '马其顿', 'cty' => 389],
    ['en' => 'Madagascar', 'iso' => 'MG', 'py' => 'm', 'zh' => '马达加斯加', 'cty' => 261],
    ['en' => 'Malawi', 'iso' => 'MW', 'py' => 'm', 'zh' => '马拉维', 'cty' => 265],
    ['en' => 'Malaysia', 'iso' => 'MY', 'py' => 'm', 'zh' => '马来西亚', 'cty' => 60],
    ['en' => 'Maldives', 'iso' => 'MV', 'py' => 'm', 'zh' => '马尔代夫', 'cty' => 960],
    ['en' => 'Mali', 'iso' => 'ML', 'py' => 'm', 'zh' => '马里', 'cty' => 223],
    ['en' => 'Malta', 'iso' => 'MT', 'py' => 'm', 'zh' => '马耳他', 'cty' => 356],
    ['en' => 'Martinique', 'iso' => 'MQ', 'py' => 'm', 'zh' => '马提尼克', 'cty' => 596],
    ['en' => 'Mauritania', 'iso' => 'MR', 'py' => 'm', 'zh' => '毛里塔尼亚', 'cty' => 222],
    ['en' => 'Mauritius', 'iso' => 'MU', 'py' => 'm', 'zh' => '毛里求斯', 'cty' => 230],
    ['en' => 'Mayotte', 'iso' => 'YT', 'py' => 'm', 'zh' => '马约特', 'cty' => 269],
    ['en' => 'Mexico', 'iso' => 'MX', 'py' => 'm', 'zh' => '墨西哥', 'cty' => 52],
    ['en' => 'Moldova', 'iso' => 'MD', 'py' => 'm', 'zh' => '摩尔多瓦', 'cty' => 373],
    ['en' => 'Monaco', 'iso' => 'MC', 'py' => 'm', 'zh' => '摩纳哥', 'cty' => 377],
    ['en' => 'Mongolia', 'iso' => 'MN', 'py' => 'm', 'zh' => '蒙古', 'cty' => 976],
    ['en' => 'Montenegro', 'iso' => 'ME', 'py' => 'h', 'zh' => '黑山', 'cty' => 382],
    ['en' => 'Montserrat', 'iso' => 'MS', 'py' => 'm', 'zh' => '蒙特塞拉特岛', 'cty' => 1664],
    ['en' => 'Morocco', 'iso' => 'MA', 'py' => 'm', 'zh' => '摩洛哥', 'cty' => 212],
    ['en' => 'Mozambique', 'iso' => 'MZ', 'py' => 'm', 'zh' => '莫桑比克', 'cty' => 258],
    ['en' => 'Myanmar', 'iso' => 'MM', 'py' => 'm', 'zh' => '缅甸', 'cty' => 95],
    ['en' => 'Namibia', 'iso' => 'NA', 'py' => 'n', 'zh' => '纳米比亚', 'cty' => 264],
    ['en' => 'Nepal', 'iso' => 'NP', 'py' => 'n', 'zh' => '尼泊尔', 'cty' => 977],
    ['en' => 'Netherlands', 'iso' => 'NL', 'py' => 'h', 'zh' => '荷兰', 'cty' => 31],
    ['en' => 'New Caledonia', 'iso' => 'NC', 'py' => 'x', 'zh' => '新喀里多尼亚', 'cty' => 687],
    ['en' => 'New Zealand', 'iso' => 'NZ', 'py' => 'x', 'zh' => '新西兰', 'cty' => 64],
    ['en' => 'Nicaragua', 'iso' => 'NI', 'py' => 'n', 'zh' => '尼加拉瓜', 'cty' => 505],
    ['en' => 'Niger', 'iso' => 'NE', 'py' => 'n', 'zh' => '尼日尔', 'cty' => 227],
    ['en' => 'Nigeria', 'iso' => 'NG', 'py' => 'n', 'zh' => '尼日利亚', 'cty' => 234],
    ['en' => 'Norway', 'iso' => 'NO', 'py' => 'n', 'zh' => '挪威', 'cty' => 47],
    ['en' => 'Oman', 'iso' => 'OM', 'py' => 'a', 'zh' => '阿曼', 'cty' => 968],
    ['en' => 'Pakistan', 'iso' => 'PK', 'py' => 'b', 'zh' => '巴基斯坦', 'cty' => 92],
    ['en' => 'Palau', 'iso' => 'PW', 'py' => 'p', 'zh' => '帕劳', 'cty' => 680],
    ['en' => 'Palestine', 'iso' => 'BL', 'py' => 'b', 'zh' => '巴勒斯坦', 'cty' => 970],
    ['en' => 'Panama', 'iso' => 'PA', 'py' => 'b', 'zh' => '巴拿马', 'cty' => 507],
    ['en' => 'Papua New Guinea', 'iso' => 'PG', 'py' => 'b', 'zh' => '巴布亚新几内亚', 'cty' => 675],
    ['en' => 'Paraguay', 'iso' => 'PY', 'py' => 'b', 'zh' => '巴拉圭', 'cty' => 595],
    ['en' => 'Peru', 'iso' => 'PE', 'py' => 'm', 'zh' => '秘鲁', 'cty' => 51],
    ['en' => 'Philippines', 'iso' => 'PH', 'py' => 'f', 'zh' => '菲律宾', 'cty' => 63],
    ['en' => 'Poland', 'iso' => 'PL', 'py' => 'b', 'zh' => '波兰', 'cty' => 48],
    ['en' => 'Portugal', 'iso' => 'PT', 'py' => 'p', 'zh' => '葡萄牙', 'cty' => 351],
    ['en' => 'Puerto Rico', 'iso' => 'PR', 'py' => 'b', 'zh' => '波多黎各', 'cty' => 1787],
    ['en' => 'Qatar', 'iso' => 'QA', 'py' => 'k', 'zh' => '卡塔尔', 'cty' => 974],
    ['en' => 'Republic Of The Congo', 'iso' => 'CG', 'py' => 'g', 'zh' => '刚果共和国', 'cty' => 242],
    ['en' => 'Réunion Island', 'iso' => 'RE', 'py' => 'l', 'zh' => '留尼汪', 'cty' => 262],
    ['en' => 'Romania', 'iso' => 'RO', 'py' => 'l', 'zh' => '罗马尼亚', 'cty' => 40],
    ['en' => 'Russia', 'iso' => 'RU', 'py' => 'e', 'zh' => '俄罗斯', 'cty' => 7],
    ['en' => 'Rwanda', 'iso' => 'RW', 'py' => 'l', 'zh' => '卢旺达', 'cty' => 250],
    ['en' => 'Saint Kitts and Nevis', 'py' => 's', 'iso' => 'KN', 'zh' => '圣基茨和尼维斯', 'cty' => 1869],
    ['en' => 'Saint Lucia', 'iso' => 'LC', 'py' => 's', 'zh' => '圣露西亚', 'cty' => 1758],
    ['en' => 'Saint Pierre and Miquelon', 'iso' => 'PM', 'py' => 's', 'zh' => '圣彼埃尔和密克隆岛', 'cty' => 508],
    ['en' => 'Saint Vincent and The Grenadines', 'iso' => 'VC', 'py' => 's', 'zh' => '圣文森特和格林纳丁斯', 'cty' => 1784],
    ['en' => 'Samoa', 'iso' => 'WS', 'py' => 's', 'zh' => '萨摩亚', 'cty' => 685],
    ['en' => 'San Marino', 'iso' => 'SM', 'py' => 's', 'zh' => '圣马力诺', 'cty' => 378],
    ['en' => 'Sao Tome and Principe', 'iso' => 'ST', 'py' => 's', 'zh' => '圣多美和普林西比', 'cty' => 239],
    ['en' => 'Saudi Arabia', 'iso' => 'SA', 'py' => 's', 'zh' => '沙特阿拉伯', 'cty' => 966],
    ['en' => 'Senegal', 'iso' => 'SN', 'py' => 's', 'zh' => '塞内加尔', 'cty' => 221],
    ['en' => 'Serbia', 'iso' => 'RS', 'py' => 's', 'zh' => '塞尔维亚', 'cty' => 381],
    ['en' => 'Seychelles', 'iso' => 'SC', 'py' => 's', 'zh' => '塞舌尔', 'cty' => 248],
    ['en' => 'Sierra Leone', 'iso' => 'SL', 'py' => 's', 'zh' => '塞拉利昂', 'cty' => 232],
    ['en' => 'Singapore', 'iso' => 'SG', 'py' => 'x', 'zh' => '新加坡', 'cty' => 65],
    ['en' => 'Saint Maarten (Dutch Part)', 'iso' => 'SX', 'py' => 's', 'zh' => '圣马丁岛（荷兰部分）', 'cty' => 1721],
    ['en' => 'Slovakia', 'iso' => 'SK', 'py' => 's', 'zh' => '斯洛伐克', 'cty' => 421],
    ['en' => 'Slovenia', 'iso' => 'SI', 'py' => 's', 'zh' => '斯洛文尼亚', 'cty' => 386],
    ['en' => 'Solomon Islands', 'iso' => 'SB', 'py' => 's', 'zh' => '所罗门群岛', 'cty' => 677],
    ['en' => 'Somalia', 'iso' => 'SO', 'py' => 's', 'zh' => '索马里', 'cty' => 252],
    ['en' => 'South Africa', 'iso' => 'ZA', 'py' => 'n', 'zh' => '南非', 'cty' => 27],
    ['en' => 'South Korea', 'iso' => 'KR', 'py' => 'h', 'zh' => '韩国', 'cty' => 82],
    ['en' => 'Spain', 'iso' => 'ES', 'py' => 'x', 'zh' => '西班牙', 'cty' => 34],
    ['en' => 'Sri Lanka', 'iso' => 'LK', 'py' => 's', 'zh' => '斯里兰卡', 'cty' => 94],
    ['en' => 'Sudan', 'iso' => 'SD', 'py' => 's', 'zh' => '苏丹', 'cty' => 249],
    ['en' => 'Suriname', 'iso' => 'SR', 'py' => 's', 'zh' => '苏里南', 'cty' => 597],
    ['en' => 'Swaziland', 'iso' => 'SZ', 'py' => 's', 'zh' => '斯威士兰', 'cty' => 268],
    ['en' => 'Sweden', 'iso' => 'SE', 'py' => 'r', 'zh' => '瑞典', 'cty' => 46],
    ['en' => 'Switzerland', 'iso' => 'CH', 'py' => 'r', 'zh' => '瑞士', 'cty' => 41],
    ['en' => 'Syria', 'iso' => 'SY', 'py' => 'x', 'zh' => '叙利亚', 'cty' => 963],
    ['en' => 'Taiwan', 'iso' => 'TW', 'py' => 'z', 'zh' => '中国台湾', 'cty' => 886],
    ['en' => 'Tajikistan', 'iso' => 'TJ', 'py' => 't', 'zh' => '塔吉克斯坦', 'cty' => 992],
    ['en' => 'Tanzania', 'iso' => 'TZ', 'py' => 't', 'zh' => '坦桑尼亚', 'cty' => 255],
    ['en' => 'Thailand', 'iso' => 'TH', 'py' => 't', 'zh' => '泰国', 'cty' => 66],
    ['en' => 'Timor-Leste', 'iso' => 'TL', 'py' => 'd', 'zh' => '东帝汶', 'cty' => 670],
    ['en' => 'Togo', 'iso' => 'TG', 'py' => 'd', 'zh' => '多哥', 'cty' => 228],
    ['en' => 'Tonga', 'iso' => 'TO', 'py' => 't', 'zh' => '汤加', 'cty' => 676],
    ['en' => 'Trinidad and Tobago', 'iso' => 'TT', 'py' => 't', 'zh' => '特立尼达和多巴哥', 'cty' => 1868],
    ['en' => 'Tunisia', 'iso' => 'TN', 'py' => 't', 'zh' => '突尼斯', 'cty' => 216],
    ['en' => 'Turkey', 'iso' => 'TR', 'py' => 't', 'zh' => '土耳其', 'cty' => 90],
    ['en' => 'Turkmenistan', 'iso' => 'TM', 'py' => 't', 'zh' => '土库曼斯坦', 'cty' => 993],
    ['en' => 'Turks and Caicos Islands', 'py' => 't', 'iso' => 'TC', 'zh' => '特克斯和凯科斯群岛', 'cty' => 1649],
    ['en' => 'Uganda', 'iso' => 'UG', 'py' => 'w', 'zh' => '乌干达', 'cty' => 256],
    ['en' => 'Ukraine', 'iso' => 'UA', 'py' => 'w', 'zh' => '乌克兰', 'cty' => 380],
    ['en' => 'United Arab Emirates', 'iso' => 'AE', 'py' => 'a', 'zh' => '阿拉伯联合酋长国', 'cty' => 971],
    ['en' => 'United Kingdom', 'iso' => 'GB', 'py' => 'y', 'zh' => '英国', 'cty' => 44],
    ['en' => 'United States', 'iso' => 'US', 'py' => 'm', 'zh' => '美国', 'cty' => 1],
    ['en' => 'Uruguay', 'iso' => 'UY', 'py' => 'w', 'zh' => '乌拉圭', 'cty' => 598],
    ['en' => 'Uzbekistan', 'iso' => 'UZ', 'py' => 'w', 'zh' => '乌兹别克斯坦', 'cty' => 998],
    ['en' => 'Vanuatu', 'iso' => 'VU', 'py' => 'w', 'zh' => '瓦努阿图', 'cty' => 678],
    ['en' => 'Venezuela', 'iso' => 'VE', 'py' => 'w', 'zh' => '委内瑞拉', 'cty' => 58],
    ['en' => 'Vietnam', 'iso' => 'VN', 'py' => 'y', 'zh' => '越南', 'cty' => 84],
    ['en' => 'Virgin Islands, British', 'iso' => 'VG', 'py' => 'y', 'zh' => '英属处女群岛', 'cty' => 1340],
    ['en' => 'Virgin Islands, US', 'iso' => 'VI', 'py' => 'y', 'zh' => '美属维尔京群岛', 'cty' => 1284],
    ['en' => 'Yemen', 'iso' => 'YE', 'py' => 'y', 'zh' => '也门', 'cty' => 967],
    ['en' => 'Zambia', 'iso' => 'ZM', 'py' => 'z', 'zh' => '赞比亚', 'cty' => 260],
    ['en' => 'Zimbabwe', 'iso' => 'ZW', 'py' => 'j', 'zh' => '津巴布韦', 'cty' => 263],
];
