<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Migration auto-generated by Sequel Pro Laravel Export (1.8.1)
 * @see https://github.com/cviebrock/sequel-pro-laravel-export
 */
class CreateSysAppVersionTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('sys_app_version', function (Blueprint $table) {
            $table->increments('id');
            $table->string('title', 50)->default('')->comment('版本号');
            $table->text('description')->comment('描述');
            $table->string('download_url', 255)->default('')->comment('下载地址');
            $table->tinyInteger('is_upgrade')->default(0)->comment('是否强制升级当前版本');
            $table->string('platform', 50)->default('')->comment('操作平台 android ios');
            $table->nullableTimestamps();

            $table->charset   = 'utf8';
            $table->collation = 'utf8_general_ci';
        });

    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('sys_app_version');
    }
}
